### ISSUE TITLE
LiuChan toolbar button wrong state

### ISSUE THREAD

**Issue by manyfew** [Paperfeed/LiuChan#8]
I've noticed some times the LiuChan toolbar button is red but LiuChan is not really active (the button really should be gray). If I click the button, it stays red and LiuChan finally becomes enabled.

I've also noticed some times LiuChan highlights Chinese characters but the pop-up does not show. Reloading the web page usually fixes this.

Thanks :)

**Comment by manyfew** [comment]
This problem didn't happen so much at the beginning, it's very strange. What is really happening is this: LiuChan _is_ active and the red icon reflects this, but then suddenly it stops working, while the icon remains red. The solution is to click the icon twice to "wake it up".

**Comment by Paperfeed** [comment]
I've had this happen to me several times as well. I think I've solved it -
will upload a patch this evening. Not entirely sure if it's fixed, but I
believe it had to do with new windows being created and the extension not
properly sending along the configuration to the new window (as it only
propagated state on tab change, not on window focus). I'll just push out
the patch and see if it occurs again or not.

Also the icon would show up red/active upon first loading (without actually
enabling itself), which it should not, so I've fixed that.

**Comment by manyfew** [comment]
Hi, did you upload this update to the Chrome store? There it still says it's at version 1.1.0, thank you

**Comment by Paperfeed** [comment]
Update has been pushed. I also added a notepad functionality (available on
right clicking the icon). Took a bit longer due to life interfering :)

**Comment by manyfew** [comment]
Much appreciated! I'm testing now. It seems to be working well so far.

The new Notepad is very interesting. I'm not sure what your intended use is but I can think of a couple of ways to put it to good use. I've posted a few suggestions for this feature on a separate thread.

**Comment by manyfew** [comment]
Actually, been testing this for a bit now and it seems it's still broken. If you use Liuchan regularly I'm sure you will have noticed.

**Comment by manyfew** [comment]
Hey, just wondering if you managed to figure this out, thanks!

**Comment by Paperfeed** [comment]
I'm currently traveling. Haven't had time to check. It's weird though
because I haven't been able to replicate it anymore. Do you have any idea
what causes it to happen? After how long/ which actions does it seem to
occur? After you switch tabs/ windows? On the same page? Any other details
would be greatly appreciated.

**Comment by manyfew** [comment]
No worries :)

I‘ve done some digging and I can reproduce the problem as follows:

1. Ensure LiuChan is already enabled (icon is red).
2. Open a new tab.
3. Type www.baidu.com in the address bar, press Enter key and wait for page to load.
4. At the top of the Baidu's home page there are some Chinese characters; move the mouse pointer over them and you should see LiuChan's pop-up. So far so good, LiuChan is working correctly.
5. Now, in the Baidu search box, type some text, for example, 你好吗 and press Enter key if necessary (it should search automatically without you having to press Enter).
6. The search results should contain plenty of Chinese characters, now move the mouse over some of those Chinese characters. Note that the LiuChan icon is still red.

**Expected result:** LiuChan pop-up is displayed as mouse passes over Chinese characters.
**Actual result:** LiuChan group-highlights the Chinese words correctly, but the pop-up never displays.

7. Click the Reload button in Chrome to refresh the page and repeat Step 6 (move mouse over Chinese characters, again).

**Result:** After reloading the page, LiuChan works again.

8. Repeat Steps 1-6 again to reproduce the problem one more time.
9. Ensure the pop-up isn't working, then click the LiuChan icon. The icon should turn gray.
10. Click the icon one more time, it should turn red.
11. Now move the mouse over some Chinese text.

**Result:** After turning LiuChan off and on again, the pop-up works correctly.

I hope that helps, have fun travelling!

**Comment by Paperfeed** [comment]
Thank you very much for the beautiful bug report! (Have you done this
before?)

I found where the problem lies and (to my knowledge) fixed the issue, along
with another serious big that only affected new users. All in all, a good
day for LiuChan :)

Apologies for the delay. I'm still on the road, but 'found' some time to
have a look :d

Again, thank you for he continued support with all the bug reports and
suggestions :)

On Sun, Feb 25, 2018 at 10:26 PM, Manuel Fernandez <notifications@github.com

**Comment by manyfew** [comment]
It finally seems to be working, awesome update! And yes, I report bugs all the time ;) I'll test it for a week or so and report. Much appreciated!

**Comment by manyfew** [comment]
It's working well. The only thing is every time I start Chrome, LiuChan is disabled by default. Would it be possible to add a setting under 'General' to specify start-up state, for example:

`Start: [Enabled | Disabled | Last]`
